### ISSUE TITLE
应该加一个只更改境外解析的选项

### ISSUE THREAD

**Issue by asplun** [gacjie/cf2dns#1]
应该加一个只更改境外解析的选项，各种场景就齐活了

**Comment by gacjie** [comment]
境外不需要优选
cf是泛播的在境外是就近原则
任何cf的IP 在海外访问都会被路由到本地机房
比如你是新加坡的请求任何cf的网站都会走新加坡的机房
国内因为要备案才能用本地机房
因此流量都会路由到海外节点
