### ISSUE TITLE
请求添加NS服务商

### ISSUE THREAD

**Issue by 498653303** [gacjie/cf2dns#14]
能不能都用CF，不喜欢分开管理域名，好难受···

**Comment by gacjie** [comment]
这个问题已经在常见问题中说过了

Q：为什么不支持海外dns解析运营商？
A：由于cf等cdn属于泛播，移动联通电信需要单独解析，才能实现三网优选。海外dns均不支持国内三网线路解析。
A：如不方便使用国内云解析 可以访问 https://www.182682.xyz/ 获取公共cname地址使用。
