### ISSUE TITLE
有考虑独立项目吗？

### ISSUE THREAD

**Issue by superen7527** [gacjie/cf2dns#2]
宝塔口碑太差了，而且一般不用他接管80端口。感觉依赖宝塔反而浪费这个项目了。

**Comment by muziqiu2** [comment]
有独立项目的啊，这个项目也是依赖于那个项目的。只要有python环境就可以运行

**Comment by gacjie** [comment]
目前提供三种部署方法 应该是够用了

[宝塔安装cf2dns插件](https://github.com/gacjie/cf2dns/wiki/宝塔安装cf2dns插件)   
[python3部署运行cf2dns_global](https://github.com/gacjie/cf2dns/wiki/python3部署运行cf2dns_global)  
[GitHub Actions 运行cf2dns_actions](https://github.com/gacjie/cf2dns/wiki/GitHub-Actions-运行cf2dns_actions)  

另外观察到https://github.com/netcccyun/dnsmgr项目也已经支持了
