### ISSUE TITLE
那个公共cft的cname域名具体应该如何使用？

### ISSUE THREAD

**Issue by xibaluo** [gacjie/cf2dns#6]
https://monitor.gacjie.cn/page/cloudfront/cname.html
因为我的域名都是放在cloudflare上面解析的，这个公共的cname应该如何配置呢？
多谢。

**Comment by gacjie** [comment]
cft是亚马逊那个aws cdn 
域名添加到亚马逊那边
解析直接使用cname记录解析到优选地址即可
切记cf那边不要开小云朵

**Comment by xibaluo** [comment]
> cft是亚马逊那个aws cdn
> 域名添加到亚马逊那边
> 解析直接使用cname记录解析到优选地址即可
> 切记cf那边不要开小云朵

具体怎么操作呢？
比如我的域名是a.cf
“域名添加到亚马逊那边 ” 这一步是把我的 a.cf加到aws的cft配置吗？
“ 解析直接使用cname记录解析到优选地址即可”  这里是在cloudflare域名配置里面把	*.cloudfront.182682.xyz	cname 到 a.cf吗？
这个182682.xyz是你的域名，我在我的域名下配置不能生效吧
多谢！

**Comment by gacjie** [comment]
优选域名只是为了方便提供IP更新
您的网站域名正常添加到系统中后
可以用优选域名替换您默认分配的*.cloudfront.net 域名
